# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np
print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [3]:
arr = np.array([2, 4, 6, 8, 10])
print(arr)
print(type(arr))


[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [5]:
zeros_arr = np.zeros(10)
ones_arr = np.ones(8)
full_arr = np.full(6, 7)

print(zeros_arr)
print(ones_arr)
print(full_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [6]:
arr1 = np.arange(1, 21)
arr2 = np.arange(2, 21, 2)

print(arr1)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [7]:
linspace_arr = np.linspace(0, 1, 11)
print(linspace_arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [8]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [9]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

2
(3, 4)
12
int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [10]:
float_arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = float_arr.astype(int)

print(int_arr)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [11]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr[0])
print(arr[-1])
print(arr[2:6])
print(arr[::2])

10
80
[30 40 50 60]
[10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [14]:
import numpy as np

matrix = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12]])

In [15]:
print("\n1. Елемент 7:", elem_7)


1. Елемент 7: 7


In [16]:
print("2. Другий рядок:", second_row)

2. Другий рядок: [5 6 7 8]


In [17]:
print("3. Третій стовпець:", third_column)


3. Третій стовпець: [ 3  7 11]


In [18]:
print("4. Підматриця (останні 2 рядки, перші 2 стовпці):\n", submatrix)

4. Підматриця (останні 2 рядки, перші 2 стовпці):
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [19]:
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [20]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [21]:
arr = np.array([4, 8, 15, 16, 23, 42])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))

108
18.0
4
42
15.5
12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [22]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.sum(matrix))
print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))
print(np.mean(matrix, axis=0))

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [23]:
arr = np.arange(1, 11)

print(np.square(arr))
print(np.sqrt(arr))
print(np.log(arr))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [24]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print(arr[arr > 15])
print(arr[arr % 2 == 0])
print(arr[(arr >= 10) & (arr <= 30)])

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [25]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [27]:
np.random.seed(42)
arr = np.random.randint(0, 101, 20)

greater_than_50 = np.sum(arr > 50)
less_or_equal_50 = np.sum(arr <= 50)

print("Масив:", arr)
print("Більші за 50:", greater_than_50)
print("Менші або дорівнюють 50:", less_or_equal_50)

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Більші за 50: 12
Менші або дорівнюють 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [28]:
arr = np.arange(1, 25)

m_4x6 = arr.reshape(4, 6)
print(m_4x6.shape)

m_6x4 = arr.reshape(6, 4)
print(m_6x4.shape)

arr_3d = arr.reshape(2, 3, 4)
print(arr_3d.shape)


(4, 6)
(6, 4)
(2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [29]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Вертикальне об'єднання
v_concat = np.vstack((A, B))
print(v_concat)

# Горизонтальне об'єднання
h_concat = np.hstack((A, B))
print(h_concat)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [30]:
matrix = np.arange(1, 13).reshape(3, 4)

flat_arr = matrix.flatten()
ravel_arr = matrix.ravel()

print("flatten():", flat_arr)
print("ravel():", ravel_arr)
print("Результати однакові за вмістом:", np.array_equal(flat_arr, ravel_arr))

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Результати однакові за вмістом: True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [31]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Сума векторів
print(a + b)

# Різниця векторів
print(a - b)

# Множення на число 3
print(a * 3)
print(b * 3)

[ 3  7 11]
[1 1 1]
[ 6 12 18]
[ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_func = np.dot(a, b)
dot_op = a @ b

print("np.dot():", dot_func)
print("Оператор @:", dot_op)

np.dot(): 32
Оператор @: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [33]:
v = np.array([3, 4])

# Евклідова норма (довжина вектора)
norm = np.linalg.norm(v)
print("Евклідова норма:", norm)

# Нормалізація (вектор одиничної довжини)
v_normalized = v / norm
print("Нормалізований вектор:", v_normalized)

Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [34]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_prod = np.cross(a, b)

print(cross_prod)

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [35]:
a = np.array([1, 2])
b = np.array([2, 1])

# Скалярний добуток та норми векторів
dot_product = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

# Косинус кута
cos_theta = dot_product / (norm_a * norm_b)

# Кут у радіанах та градусах
angle_radians = np.arccos(cos_theta)
angle_degrees = np.degrees(angle_radians)

print("Косинус кута:", cos_theta)
print("Кут у градусах:", angle_degrees)

Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [36]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

transposed_T = A.T
transposed_func = np.transpose(A)

print("Використання .T:\n", transposed_T)
print("\nВикористання np.transpose():\n", transposed_func)

Використання .T:
 [[1 4]
 [2 5]
 [3 6]]

Використання np.transpose():
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [37]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

# Поелементний добуток (Hadamard product):
# Кожен елемент матриці A множиться на відповідний елемент матриці B (a_ij * b_ij)
elementwise = A * B

# Матричний добуток (Matrix multiplication):
# Обчислюється як скалярний добуток рядків матриці A та стовпців матриці B
matrix_mult = A @ B

print("Поелементний добуток (A * B):\n", elementwise)
print("\nМатричний добуток (A @ B):\n", matrix_mult)

Поелементний добуток (A * B):
 [[2 0]
 [3 8]]

Матричний добуток (A @ B):
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [38]:
A = np.array([[4, 7],
              [2, 6]])

# Визначник
det_A = np.linalg.det(A)

# Обернена матриця
inv_A = np.linalg.inv(A)

# Перевірка (A @ A_inv має дорівнювати одиничній матриці I)
check = A @ inv_A

print("Визначник:", det_A)
print("\nОбернена матриця:\n", inv_A)
print("\nПеревірка (A @ A^-1):\n", check)

Визначник: 10.000000000000002

Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка (A @ A^-1):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [39]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

# Розв'язок системи лінійних рівнянь Ax = b
x = np.linalg.solve(A, b)

print("Розв'язок (x, y):", x)

Розв'язок (x, y): [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [40]:
# Одинична матриця 4x4
I = np.eye(4)

# Довільна матриця 4x4
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Множення на одиничну матрицю
result = A @ I

print("Одинична матриця:\n", I)
print("\nРезультат множення (A @ I):\n", result)
print("\nРезультат збігається з початковою матрицею:", np.allclose(A, result))

Одинична матриця:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Результат множення (A @ I):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Результат збігається з початковою матрицею: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [41]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = A + 10

print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])

result = A + v

print(result)

# Аналіз broadcasting:
# Вектор v має форму (3,), а матриця A — (3, 3).
# NumPy віртуально розтягує вектор v уздовж першої осі (одним виміром догори),
# перетворюючи його на матрицю форми (3, 3), де кожен рядок дорівнює [10, 20, 30].
# Після цього виконується поелементне додавання.

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [43]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

# Середнє та стандартне відхилення для кожного стовпця (axis=0)
mean = np.mean(A, axis=0)
std = np.std(A, axis=0)

# Z-score нормалізація за допомогою broadcasting
normalized_A = (A - mean) / std

print(normalized_A)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [44]:
np.random.seed(42)

# 10 випадкових цілих чисел від 1 до 100
rand_integers = np.random.randint(1, 101, size=10)

# Матриця 3x3 випадкових чисел від 0 до 1
rand_matrix = np.random.rand(3, 3)

# 1000 значень із нормального розподілу
rand_normal = np.random.randn(1000)

# Обчислення статистик
mean_val = np.mean(rand_normal)
std_val = np.std(rand_normal)

print("Цілі числа від 1 до 100:\n", rand_integers)
print("\nМатриця 3x3 [0, 1):\n", rand_matrix)
print("\nСереднє значення:", mean_val)
print("Стандартне відхилення:", std_val)

Цілі числа від 1 до 100:
 [52 93 15 72 61 21 83 87 75 75]

Матриця 3x3 [0, 1):
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

Середнє значення: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [45]:
np.random.seed(42)

# Моделювання оцінок 30 студентів
grades = np.random.randint(0, 101, size=30)

# Статистичні показники
mean_grade = np.mean(grades)
median_grade = np.median(grades)
max_grade = np.max(grades)
min_grade = np.min(grades)

# Кількісні та відсоткові показники
passed_count = np.sum(grades >= 60)
top_percentage = np.mean(grades >= 90) * 100

print("Оцінки студентів:\n", grades)
print("\nСередня оцінка:", mean_grade)
print("Медіана:", median_grade)
print("Найвища оцінка:", max_grade)
print("Найнижча оцінка:", min_grade)
print("Кількість студентів з оцінкою >= 60:", passed_count)
print(f"Відсоток студентів з оцінкою >= 90: {top_percentage:.2f}%")

Оцінки студентів:
 [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]

Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища оцінка: 99
Найнижча оцінка: 1
Кількість студентів з оцінкою >= 60: 13
Відсоток студентів з оцінкою >= 90: 6.67%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [46]:
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])

# Загальний обсяг продажів кожного товару (сума по рядочках)
total_per_product = np.sum(sales, axis=1)

# Загальний обсяг продажів у кожному місяці (сума по стовпчиках)
total_per_month = np.sum(sales, axis=0)

# Товар із найбільшими сумарними продажами (індекс + 1)
best_product_idx = np.argmax(total_per_product) + 1

# Місяць із найбільшим загальним обсягом продажів (індекс + 1)
best_month_idx = np.argmax(total_per_month) + 1

# Середній обсяг продажів кожного товару
mean_per_product = np.mean(sales, axis=1)

print("Загальні продажі за товарами (1, 2, 3):", total_per_product)
print("Загальні продажі за місяцями (1, 2, 3, 4):", total_per_month)
print("Товар з найбільшими продажами:", best_product_idx)
print("Місяць з найбільшими продажами:", best_month_idx)
print("Середні продажі за товарами:", mean_per_product)

Загальні продажі за товарами (1, 2, 3): [600 380 820]
Загальні продажі за місяцями (1, 2, 3, 4): [400 420 480 500]
Товар з найбільшими продажами: 3
Місяць з найбільшими продажами: 4
Середні продажі за товарами: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [47]:
np.random.seed(42)

# Створення матриці 5x5 із випадкових цілих чисел від 1 до 20
A = np.random.randint(1, 21, size=(5, 5))

# 1. Сума головної діагоналі
main_diag_sum = np.trace(A)

# 2. Сума побічної діагоналі
sec_diag_sum = np.trace(np.fliplr(A))

# 3. Максимальний елемент кожного рядка
max_per_row = np.max(A, axis=1)

# 4. Мінімальний елемент кожного стовпця
min_per_col = np.min(A, axis=0)

# 5. Заміна елементів, менших за середнє значення всей матриці, на 0
A_modified = A.copy()
A_modified[A_modified < np.mean(A)] = 0

print("Початкова матриця A:\n", A)
print("\nСума головної діагоналі:", main_diag_sum)
print("Сума побічної діагоналі:", sec_diag_sum)
print("Максимуми по рядках:", max_per_row)
print("Мінімуми по стовпцях:", min_per_col)
print("\nМатриця після заміни елементів < mean на 0:\n", A_modified)

Початкова матриця A:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]

Сума головної діагоналі: 59
Сума побічної діагоналі: 32
Максимуми по рядках: [20 19 12 17 19]
Мінімуми по стовпцях: [ 2  1  2 11  4]

Матриця після заміни елементів < mean на 0:
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [48]:
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

# Евклідова відстань між рядками
dist_1_2 = np.linalg.norm(X[0] - X[1])
dist_1_3 = np.linalg.norm(X[0] - X[2])
dist_2_3 = np.linalg.norm(X[1] - X[2])

print("Відстань між 1 та 2 рядком:", dist_1_2)
print("Відстань між 1 та 3 рядком:", dist_1_3)
print("Відстань між 2 та 3 рядком:", dist_2_3)

Відстань між 1 та 2 рядком: 1.7320508075688772
Відстань між 1 та 3 рядком: 5.196152422706632
Відстань між 2 та 3 рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [49]:
np.random.seed(42)

# Створення матриці 4x4 із довільних цілих чисел
A = np.random.randint(1, 10, size=(4, 4))

# Норма кожного рядка (axis=1), keepdims=True для збереження форми (4, 1) та сумісності з broadcasting
row_norms = np.linalg.norm(A, axis=1, keepdims=True)

# Нормалізація кожного рядка до одиничної довжини
A_normalized = A / row_norms

print("Початкова матриця:\n", A)
print("\nНорми рядків:\n", row_norms)
print("\nНормалізована матриця:\n", A_normalized)

Початкова матриця:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

Норми рядків:
 [[12.40967365]
 [13.07669683]
 [13.        ]
 [ 8.60232527]]

Нормалізована матриця:
 [[0.56407607 0.32232919 0.64465837 0.40291148]
 [0.53530338 0.22941573 0.53530338 0.61177529]
 [0.38461538 0.30769231 0.61538462 0.61538462]
 [0.34874292 0.69748583 0.58123819 0.23249528]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [50]:
import numpy as np

# Матриця коефіцієнтів A та вектор правих частин b
A = np.array([[1,  2,  1],
              [2,  1, -1],
              [3, -1,  2]])

b = np.array([9, 8, 3])

# Розв'язок системи Ax = b
x = np.linalg.solve(A, b)

# Перевірка матричним множенням (A @ x)
b_check = A @ x

print("Розв'язок (x, y, z):", x)
print("Результат A @ x:", b_check)
print("Результат збігається з вектором b:", np.allclose(b_check, b))

Розв'язок (x, y, z): [ 2.22222222  3.44444444 -0.11111111]
Результат A @ x: [9. 8. 3.]
Результат збігається з вектором b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
